FROM nginx:1.15
# 定义作者
MAINTAINER yaosiyuan	 <yaosiyuanmail@163.com>
# 将dist文件中的内容复制到 /usr/share/nginx/html/ 这个目录下面
COPY dist/  /usr/share/nginx/html/

 ———————————————— 
版权声明：本文为CSDN博主「梦里谁知身是客」的原创文章，遵循CC 4.0 by-sa版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/wn1245343496/article/details/81912010